name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        
    - name: Build and Push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/raycloudtools
        
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        
        docker build -f ./docker/Dockerfile -t $IMAGE_ID:$VERSION .
        docker push $IMAGE_ID:$VERSION